name: exploress_location
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  utils_component:
    git:
      url: https://github.com/lordyhas/utils_component



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  latlong2: ^0.8.1
  font_awesome_flutter: any
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2

  permission_handler: ^10.2.0

  firebase_storage: ^11.0.2
  cloud_firestore: ^4.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2

  #flutter_facebook_auth: ^3.3.0+2
  google_sign_in: ^5.4.2

  pedantic: ^1.11.0
  formz: ^0.4.1

  badges: ^2.0.3
  url_launcher: ^6.1.6
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  local_auth: ^2.1.2
  path_provider: ^2.0.11
  share_plus: ^6.0.1

  package_info_plus: ^3.0.1
  device_info_plus: ^7.0.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

  flutter_chat_ui: ^1.4.4
  flutter_local_notifications: ^12.0.3
  flutter_app_badger: ^1.5.0

  flutter_markdown: ^0.6.13

  dotted_border: any

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
    - assets/local/
    - assets/icon_app.png
    - assets/img/bg_image_web.jpeg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
