name: exploress_rental
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.7+0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  utils_component:
    git:
      url: https://github.com/lordyhas/utils_component
  #exploress_repository:
    #path: ../packages/exploress_packages



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5
  latlong2: ^0.8.1
  font_awesome_flutter: any
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2

  permission_handler: ^10.2.0
  photo_view: ^0.14.0

  #firebase_storage: ^11.0.2

  cloud_firestore: ^4.3.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  #firebase_ui_auth: ^1.1.6

  #flutter_facebook_auth: ^3.3.0+2

  flutter_facebook_auth: ^5.0.6
  google_sign_in: ^5.4.2


  pedantic: ^1.11.0
  formz: ^0.4.1

  badges: ^2.0.3
  url_launcher: ^6.1.6
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  local_auth: ^2.1.2
  path_provider: ^2.0.11
  share_plus: ^6.0.1

  package_info_plus: ^3.0.1
  device_info_plus: ^7.0.1

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

  flutter_chat_ui: ^1.4.4
  flutter_local_notifications: ^12.0.3
  flutter_app_badger: ^1.5.0

  flutter_markdown: ^0.6.1
  dotted_border: any
  achievement_view: ^1.0.0
  logger: ^1.1.0
  pull_to_refresh: ^2.0.0

  fancy_bottom_navigation_2: ^0.3.5
  go_router: ^6.0.0

dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/img/
    - assets/local/
    - assets/avatar/
    - assets/icon_app.png



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
