// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP4xC71bNYXBp4eSOpx_k9zIgs58Gaz_Q',
    appId: '1:109870721627:web:8ad89a5103dcd442372d7e',
    messagingSenderId: '109870721627',
    projectId: 'exploressrental',
    authDomain: 'exploressrental.firebaseapp.com',
    storageBucket: 'exploressrental.appspot.com',
    measurementId: 'G-LFGJZQWQJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBls2SZwKm-oGsaD5ZnFOSLer2pSawc8Rw',
    appId: '1:109870721627:android:f1d662f3c0e2c31e372d7e',
    messagingSenderId: '109870721627',
    projectId: 'exploressrental',
    storageBucket: 'exploressrental.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSbKVbYTAOHTadTInkIWd7rCaLErImGQ',
    appId: '1:109870721627:ios:ff79150702e17cda372d7e',
    messagingSenderId: '109870721627',
    projectId: 'exploressrental',
    storageBucket: 'exploressrental.appspot.com',
    iosClientId: '109870721627-som3jtqiu5hjkelv2cqds5stc2lsh8ca.apps.googleusercontent.com',
    iosBundleId: 'com.kdynamic.exploress.kodisha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdSbKVbYTAOHTadTInkIWd7rCaLErImGQ',
    appId: '1:109870721627:ios:c7a6ff03624ce9bd372d7e',
    messagingSenderId: '109870721627',
    projectId: 'exploressrental',
    storageBucket: 'exploressrental.appspot.com',
    iosClientId: '109870721627-cpa74pa4oktqldj6sf6te1me0ur7pbj2.apps.googleusercontent.com',
    iosBundleId: 'com.kdynamic.exploress.loaction.exploressLocation',
  );
}
